<a href="https://colab.research.google.com/github/brotheramin/MachineLearning/blob/main/ReshapingData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Reshaping Data**

In [6]:
import numpy as np

In [9]:
a = np.array([[1,2] , [3,4]])
a

array([[1, 2],
       [3, 4]])

In [11]:
a.shape

(2, 2)

In [10]:
a.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [12]:
a.reshape(1,4)

array([[1, 2, 3, 4]])

In [15]:
a = np.array([[1,2,3] , [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
a.shape

(2, 3)

In [17]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
a = np.arange(0,6)
a

array([0, 1, 2, 3, 4, 5])

In [19]:
a.shape

(6,)

In [20]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])